export const FOCUS_FIELD_LABELS: Record<string, string> = {
  icp: "ICP",
  filtro_perfil: "Filtro de Perfil",
  resumo_mercado: "Resumo de Mercado",
  equacao_valor: "Equação de Valor",
  escada: "Escada de Valor",
  oferta_principal: "Oferta Principal",
  precificacao: "Precificação",
  funil_comercial: "Funil Comercial",
  sdr: "SDR",
  closer: "Closer",
  carta_vendas: "Carta de Vendas",
  pitch_stacking: "Pitch de Fechamento",
  statement: "Statement",
  narrativa: "Narrativa StoryBrand",
  pilares_conteudo: "Pilares de Conteúdo",
  linha_editorial: "Linha Editorial",
  mapa_funil: "Mapa do Funil",
  jornada_cliente: "Jornada do Cliente",
  campanhas: "Campanhas",
  angulos_criativos: "Ângulos Criativos",
  mensuracao: "Mensuração",
  checklist: "Checklist",
  hipoteses: "Hipóteses",
};
